# Generated by Django 4.1.9 on 2023-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(null=True),
        ),
    ]
