# Generated by Django 4.1.9 on 2023-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_avatar_alter_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
