# Generated by Django 4.1.9 on 2023-08-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('user', models.IntegerField()),
                ('preAnswer_ID', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('question_ID', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='ReferenceLink',
            fields=[
                ('ref_ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('answer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerService.answer')),
            ],
            options={
                'verbose_name': 'Reference link',
                'verbose_name_plural': 'Reference links',
                'db_table': 'referencelink',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('answer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerService.answer')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
    ]
