# Generated by Django 4.1.9 on 2023-08-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answerService', '0002_alter_answer_preanswer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
