# Generated by Django 4.1.9 on 2023-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_ID', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('report', models.CharField(max_length=1000)),
                ('user', models.IntegerField()),
                ('question_ID', models.IntegerField()),
                ('answer_ID', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review',
                'db_table': 'review',
            },
        ),
    ]
