# Generated by Django 4.1.9 on 2023-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='answer_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='question_ID',
            field=models.IntegerField(null=True),
        ),
    ]
