# Generated by Django 4.1.9 on 2023-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_review_answer_id_alter_review_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.BooleanField(),
        ),
    ]
