# Generated by Django 4.1.9 on 2023-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("User_ID", models.AutoField(primary_key=True, serialize=False)),
                ("User_Name", models.CharField(max_length=50)),
                ("User_Email", models.CharField(max_length=50)),
                ("User_Password", models.CharField(max_length=50)),
                ("User_Phone", models.CharField(max_length=50)),
                ("User_Address", models.CharField(max_length=50)),
                ("User_Created_Date", models.CharField(max_length=50)),
                ("User_Updated_Date", models.CharField(max_length=50)),
            ],
        ),
    ]
